language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install ujson simplejson django
  - python setup.py install
script: nosetests tests
notifications:
  email:
    recipients:
      - marselester@ya.ru
    on_success: change
    on_failure: change
